#
# ビルド
# ----
# docker-compose build
# docker-commpose -f docker-commpose-doc.yml build
# 
# ドキュメント生成
# ------------
# docker-commpose -f docker-commpose-doc.yml run doc

version: "3"
services:
  doc:
    build:
      context: doc/docker
    volumes:
      - .:/app
    # environment:
    #   - ES_ENDPOINT=${ES_ENDPOINT}
    #   - ES_INDEX_NAME=${ES_INDEX_NAME}
    #   - KIBANA_ENDPOINT=${KIBANA_ENDPOINT}
    working_dir: /app/doc
    command: make singlehtml
