version: "3"
services:
  web:
    build: .
    ports:
      # flask port 5000 -> local 5001
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - ES_ENDPOINT=${ES_ENDPOINT}
      - ES_INDEX_NAME=${ES_INDEX_NAME}
