version: "3"
services:
  web:
    build: .
    ports:
      # flask port 5000 -> local 5001
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - ES_ENDPOINT=${ES_ENDPOINT}
      - ES_INDEX_NAME=${ES_INDEX_NAME}
      - KIBANA_ENDPOINT=${KIBANA_ENDPOINT}
    command: >
      /bin/sh -c
      "envsubst < static/js/config.js.template
      > static/js/config.js
      && python app.py"
  watch:
    build: .
    volumes:
      - .:/app
    command: python watch.py
